# Yarn configuration for production builds
nodeLinker: node-modules
packageExtensions:
  "@solana/wallet-adapter-particle@*":
    dependencies:
      bs58: ^6.0.0
  "@keystonehq/sdk@*":
    dependencies:
      react: 18.2.0
      react-dom: 18.2.0
  "react-qr-reader@*":
    dependencies:
      react: 18.2.0
      react-dom: 18.2.0
  "@react-native/codegen@*":
    dependencies:
      "@babel/preset-env": ^7.22.0
  "jscodeshift@*":
    dependencies:
      "@babel/preset-env": ^7.22.0